from enum import Enum


class ConversationState(str, Enum):

    START_CALL = "START_CALL"

    ASK_CUSTOMER_NAME = "ASK_CUSTOMER_NAME"

    INTRODUCE_SELF = "INTRODUCTION"

    ASK_TALK_TIME = "ASK_TALK_TIME"

    ASK_CONNECTION_COUNT = "ASK_CONNECTION_COUNT"

    ASK_CONNECTION_TYPE = "ASK_CONNECTION_TYPE"

    ASK_OPERATOR = "ASK_OPERATOR"

    PLAN_INTRO = "PLAN_INTRO"

    EXISTING_CUSTOMER = "EXISTING_CUSTOMER"

    RECOMMEND_PLAN = "RECOMMEND_PLAN"

    ASK_BUSINESS_TYPE = "ASK_BUSINESS_TYPE"

    COLLECT_DOCUMENTS = "COLLECT_DOCUMENTS"

    SCHEDULE_PICKUP = "SCHEDULE_PICKUP"

    CALLBACK = "CALLBACK"

    CLOSE = "CLOSE"


    